// FunctionRegistry.cpp - Built-in expression function metadata.
#include "FunctionRegistry.h"

#include <array>

namespace XpressFormula::Core {

namespace {

constexpr auto kFunctions = std::to_array<FunctionInfo>({
    { FunctionId::Sin, "sin", "sin(a)", "sine of an angle in radians", "Trigonometry",
      "Computes the sine of an angle measured in radians. Useful for waves, oscillation, and periodic surface detail.",
      "standard trigonometric sine", "sin(x)", 1, 1 },
    { FunctionId::Cos, "cos", "cos(a)", "cosine of an angle in radians", "Trigonometry",
      "Computes the cosine of an angle measured in radians. Useful for phase-shifted waves, circular motion, and periodic patterns.",
      "standard trigonometric cosine", "cos(x)", 1, 1 },
    { FunctionId::Tan, "tan", "tan(a)", "tangent of an angle in radians", "Trigonometry",
      "Computes tangent for an angle measured in radians. Values grow rapidly near odd multiples of pi/2.",
      "sin(a)/cos(a)", "tan(x)", 1, 1 },
    { FunctionId::Asin, "asin", "asin(a)", "inverse sine, in radians", "Trigonometry",
      "Returns the angle whose sine is a. The real-valued domain is -1 to 1.",
      "inverse of sin(a) over its principal branch", "asin(saturate(x))", 1, 1 },
    { FunctionId::Acos, "acos", "acos(a)", "inverse cosine, in radians", "Trigonometry",
      "Returns the angle whose cosine is a. The real-valued domain is -1 to 1.",
      "inverse of cos(a) over its principal branch", "acos(saturate(x))", 1, 1 },
    { FunctionId::Atan, "atan", "atan(a)", "inverse tangent, in radians", "Trigonometry",
      "Returns the principal inverse tangent of a value. Useful for angle calculations from slopes.",
      "inverse of tan(a) over its principal branch", "atan(x)", 1, 1 },
    { FunctionId::Atan2, "atan2", "atan2(y,x)", "angle of the vector from x/y components", "Trigonometry",
      "Returns the signed angle of the 2D vector (x,y), preserving quadrant information. Useful for radial patterns.",
      "quadrant-aware atan(y/x)", "atan2(y,x)", 2, 2 },
    { FunctionId::Sinh, "sinh", "sinh(a)", "hyperbolic sine", "Trigonometry",
      "Computes hyperbolic sine. It grows exponentially and can create steep analytic curves.",
      "(exp(a)-exp(-a))/2", "sinh(x)", 1, 1 },
    { FunctionId::Cosh, "cosh", "cosh(a)", "hyperbolic cosine", "Trigonometry",
      "Computes hyperbolic cosine. It is symmetric and useful for catenary-like curves.",
      "(exp(a)+exp(-a))/2", "cosh(x)-2", 1, 1 },
    { FunctionId::Tanh, "tanh", "tanh(a)", "hyperbolic tangent", "Trigonometry",
      "Computes a smooth S-shaped transition from -1 to 1. Useful for soft limiting.",
      "sinh(a)/cosh(a)", "tanh(x)", 1, 1 },

    { FunctionId::Sqrt, "sqrt", "sqrt(a)", "square root, NaN for negative input", "Basic",
      "Returns the non-negative square root. Negative inputs return NaN in the real-valued evaluator.",
      "a^0.5, for a >= 0", "sqrt(abs(x))", 1, 1 },
    { FunctionId::Cbrt, "cbrt", "cbrt(a)", "cube root", "Basic",
      "Returns the real cube root, including for negative values.",
      "real-valued cube root of a", "cbrt(x)", 1, 1 },
    { FunctionId::Abs, "abs", "abs(a)", "absolute value", "Basic",
      "Returns distance from zero on the number line. Useful for symmetry and folded shapes.",
      "a < 0 ? -a : a", "abs(x)-1", 1, 1 },
    { FunctionId::Ceil, "ceil", "ceil(a)", "round upward to an integer", "Basic",
      "Rounds a value up to the next integer. Useful for stepped patterns.",
      "smallest integer greater than or equal to a", "ceil(x)", 1, 1 },
    { FunctionId::Floor, "floor", "floor(a)", "round downward to an integer", "Basic",
      "Rounds a value down to the previous integer. Useful for cells, steps, and fractional patterns.",
      "largest integer less than or equal to a", "floor(x)", 1, 1 },
    { FunctionId::Round, "round", "round(a)", "round to nearest integer", "Basic",
      "Rounds to the nearest integer, with half values rounded away from zero.",
      "nearest integer to a", "round(x)", 1, 1 },
    { FunctionId::Log, "log", "log(a) or log(base,value)", "natural log or base-log form", "Basic",
      "Computes the natural logarithm with one argument, or a logarithm in a custom base with two arguments.",
      "log(value)/log(base) for the two-argument form", "log(2,abs(x)+1)", 1, 2 },
    { FunctionId::Log2, "log2", "log2(a)", "base-2 logarithm", "Basic",
      "Computes the logarithm in base 2. Inputs must be positive.",
      "log(a)/log(2)", "log2(abs(x)+1)", 1, 1 },
    { FunctionId::Log10, "log10", "log10(a)", "base-10 logarithm", "Basic",
      "Computes the logarithm in base 10. Inputs must be positive.",
      "log(a)/log(10)", "log10(abs(x)+1)", 1, 1 },
    { FunctionId::Exp, "exp", "exp(a)", "e raised to a power", "Basic",
      "Raises Euler's number to a power. Useful for decay curves and growth effects.",
      "e^a", "exp(-x*x)", 1, 1 },
    { FunctionId::Min, "min", "min(a,b)", "smaller of two values", "Basic",
      "Returns the smaller of two values. Useful for choosing lower fields or combining hard shape unions.",
      "a when a < b, otherwise b", "min(x,y)", 2, 2 },
    { FunctionId::Max, "max", "max(a,b)", "larger of two values", "Basic",
      "Returns the larger of two values. Useful for hard intersections and clipping implicit shapes.",
      "a when a > b, otherwise b", "max(x,y)", 2, 2 },
    { FunctionId::Pow, "pow", "pow(a,b)", "a raised to power b", "Basic",
      "Raises one value to another. Use integer powers for stable polynomial shapes.",
      "a^b", "pow(abs(x),4)", 2, 2 },
    { FunctionId::Mod, "mod", "mod(a,b)", "floating-point remainder, NaN when b is zero", "Basic",
      "Returns the floating-point remainder after dividing a by b. The result keeps the sign of a.",
      "floating-point remainder of a divided by b", "mod(x,1)", 2, 2 },
    { FunctionId::Sign, "sign", "sign(a)", "-1, 0, or 1 depending on the sign", "Basic",
      "Classifies a value as negative, zero, or positive. Useful for simple discontinuous masks.",
      "-1 if a < 0, 0 if a == 0, 1 if a > 0", "sign(x)", 1, 1 },

    { FunctionId::Hypot, "hypot", "hypot(a,b)", "2D distance from the origin", "Distance",
      "Computes a stable 2D length from two components. It is equivalent to length2 with shorter argument names.",
      "sqrt(a^2 + b^2)", "hypot(x,y)", 2, 2 },
    { FunctionId::Length2, "length2", "length2(x,y)", "2D vector length", "Distance",
      "Computes distance from the origin to the point (x,y). Useful for circles, radial waves, and falloff.",
      "sqrt(x^2 + y^2)", "sin(8*length2(x,y))", 2, 2 },
    { FunctionId::Length3, "length3", "length3(x,y,z)", "3D vector length", "Distance",
      "Computes distance from the origin to the point (x,y,z). Useful for spheres, radial waves, and implicit 3D surfaces.",
      "sqrt(x^2 + y^2 + z^2)", "length3(x,y,z)-1", 3, 3 },
    { FunctionId::Distance2, "distance2", "distance2(x1,y1,x2,y2)", "distance between two 2D points", "Distance",
      "Computes the distance between two 2D points. Useful for placing radial effects around custom centers.",
      "length2(x1-x2, y1-y2)", "distance2(x,y,1,1)", 4, 4 },
    { FunctionId::Distance3, "distance3", "distance3(x1,y1,z1,x2,y2,z2)", "distance between two 3D points", "Distance",
      "Computes the distance between two 3D points. Useful for fields centered away from the origin.",
      "length3(x1-x2, y1-y2, z1-z2)", "distance3(x,y,z,1,0,0)-0.5", 6, 6 },

    { FunctionId::Clamp, "clamp", "clamp(x,min,max)", "limit a value to a range", "Range / interpolation",
      "Limits a value to a range. Reversed bounds are swapped for convenience.",
      "min(max(x,min),max), with reversed bounds swapped", "clamp(x,0,1)", 3, 3 },
    { FunctionId::Saturate, "saturate", "saturate(x)", "clamp a value to 0..1", "Range / interpolation",
      "Clamps a value into the normalized 0 to 1 range. Useful for masks and blend weights.",
      "clamp(x,0,1)", "saturate(x)", 1, 1 },
    { FunctionId::Mix, "mix", "mix(a,b,t)", "linear blend from a to b; t may extrapolate", "Range / interpolation",
      "Linearly blends between a and b. The blend factor t is not clamped, so extrapolation is allowed.",
      "a*(1-t)+b*t", "mix(sin(x),cos(x),0.5)", 3, 3 },
    { FunctionId::Lerp, "lerp", "lerp(a,b,t)", "alias of mix(a,b,t)", "Range / interpolation",
      "Alias for mix. Use whichever name is clearer for the formula you are writing.",
      "mix(a,b,t)", "lerp(0,1,saturate(x))", 3, 3 },
    { FunctionId::InverseLerp, "inverseLerp", "inverseLerp(a,b,x)", "normalized position of x within a..b", "Range / interpolation",
      "Maps x to a clamped 0 to 1 value based on its position between a and b. Equal endpoints return NaN.",
      "clamp((x-a)/(b-a),0,1)", "inverseLerp(-1,1,x)", 3, 3 },
    { FunctionId::Remap, "remap", "remap(inMin,inMax,outMin,outMax,x)", "map x from one range into another", "Range / interpolation",
      "Maps x from one range into another using a clamped normalized position. Equal input endpoints return NaN.",
      "mix(outMin,outMax,inverseLerp(inMin,inMax,x))", "remap(-1,1,0,10,x)", 5, 5 },
    { FunctionId::Step, "step", "step(edge,x)", "0 before edge, 1 at or after edge", "Range / interpolation",
      "Creates a hard threshold. It returns 0 when x is less than edge and 1 otherwise.",
      "x < edge ? 0 : 1", "step(0,x)", 2, 2 },
    { FunctionId::Smoothstep, "smoothstep", "smoothstep(a,b,x)", "smooth clamped transition from 0 to 1", "Range / interpolation",
      "Returns a smooth transition between two edge values. Useful for soft masks, falloff, and visual blending.",
      "t*t*(3-2*t), where t = clamp((x-a)/(b-a),0,1)", "sin(8*length2(x,y))*smoothstep(3,0,length2(x,y))", 3, 3 },
    { FunctionId::Smootherstep, "smootherstep", "smootherstep(a,b,x)", "extra-smooth clamped transition", "Range / interpolation",
      "Returns a smoother transition with zero first and second derivatives at the endpoints.",
      "t^3*(t*(t*6-15)+10), where t = clamp((x-a)/(b-a),0,1)", "smootherstep(0,1,saturate(x))", 3, 3 },

    { FunctionId::Fract, "fract", "fract(x)", "fractional part using x-floor(x)", "Patterns",
      "Returns the fractional part of x. Negative values wrap upward, so fract(-0.25) is 0.75.",
      "x - floor(x)", "fract(x)", 1, 1 },
    { FunctionId::Tri, "tri", "tri(x)", "triangle wave from fractional position", "Patterns",
      "Creates a repeating triangle wave based on the fractional part of x. The phase is 1 at integer values.",
      "abs(fract(x)-0.5)*2", "tri(x)", 1, 1 },
    { FunctionId::Pulse, "pulse", "pulse(a,b,x)", "1 inside an edge interval, otherwise 0", "Patterns",
      "Creates a rectangular pulse between two edge values. Reversed edges are swapped for convenience.",
      "step(a,x)-step(b,x), with reversed edges swapped", "pulse(0.25,0.75,fract(x))", 3, 3 },
    { FunctionId::Repeat, "repeat", "repeat(x,period)", "centered repeat coordinate", "Patterns",
      "Repeats a coordinate around zero for tileable formulas. A zero period returns NaN.",
      "mod(x + period/2, period) - period/2", "repeat(x,1)", 2, 2 },

    { FunctionId::Smin, "smin", "smin(a,b,k)", "smooth minimum for blending implicit shapes", "Implicit composition",
      "Blends two signed-distance or implicit fields smoothly. Useful for soft unions between shapes.",
      "h=clamp(0.5+0.5*(b-a)/k,0,1); mix(b,a,h)-k*h*(1-h)", "smin(sdSphere(x-0.7,y,z,0.5),sdSphere(x+0.7,y,z,0.5),0.25)", 3, 3 },
    { FunctionId::Smax, "smax", "smax(a,b,k)", "smooth maximum for subtracting/blending shapes", "Implicit composition",
      "Smoothly blends maximum operations. Useful for soft intersections and soft subtraction with negated fields.",
      "-smin(-a,-b,k)", "smax(sdBox(x,y,z,1,1,1),-sdCylinderX(x,y,z,0.32),0.12)", 3, 3 },

    { FunctionId::SdSphere, "sdSphere", "sdSphere(x,y,z,r)", "signed distance to a centered sphere", "Signed distance",
      "Returns the signed distance to a sphere centered at the origin. Negative values are inside the sphere.",
      "length3(x,y,z)-r", "sdSphere(x,y,z,1)", 4, 4 },
    { FunctionId::SdBox, "sdBox", "sdBox(x,y,z,bx,by,bz)", "signed distance to a centered box", "Signed distance",
      "Returns signed distance to an axis-aligned box centered at the origin with half-extents bx, by, and bz.",
      "standard centered box SDF using abs, max, min, and length3", "sdBox(x,y,z,1,1,1)", 6, 6 },
    { FunctionId::SdTorus, "sdTorus", "sdTorus(x,y,z,R,r)", "signed distance to a centered torus", "Signed distance",
      "Returns signed distance to a torus around the Z axis. R is the major radius and r is the tube radius.",
      "length2(length2(x,y)-R,z)-r", "sdTorus(x,y,z,1.2,0.25)", 5, 5 },
    { FunctionId::SdCylinderX, "sdCylinderX", "sdCylinderX(x,y,z,r)", "signed distance to a cylinder along X", "Signed distance",
      "Returns signed distance to an infinite cylinder whose axis follows X.",
      "length2(y,z)-r", "sdCylinderX(x,y,z,0.35)", 4, 4 },
    { FunctionId::SdCylinderY, "sdCylinderY", "sdCylinderY(x,y,z,r)", "signed distance to a cylinder along Y", "Signed distance",
      "Returns signed distance to an infinite cylinder whose axis follows Y.",
      "length2(x,z)-r", "sdCylinderY(x,y,z,0.35)", 4, 4 },
    { FunctionId::SdCylinderZ, "sdCylinderZ", "sdCylinderZ(x,y,z,r)", "signed distance to a cylinder along Z", "Signed distance",
      "Returns signed distance to an infinite cylinder whose axis follows Z.",
      "length2(x,y)-r", "sdCylinderZ(x,y,z,0.35)", 4, 4 },

    { FunctionId::Noise2, "noise2", "noise2(x,y)", "deterministic 2D value noise, about -1..1", "Noise",
      "Returns deterministic 2D procedural value noise. It has no global random state and is useful for texture-like variation.",
      "Deterministic procedural noise; not expressible as a short formula using the basic functions.", "noise2(x,y)", 2, 2 },
    { FunctionId::Noise3, "noise3", "noise3(x,y,z)", "deterministic 3D value noise, about -1..1", "Noise",
      "Returns deterministic 3D procedural value noise. Useful for bumpy implicit surfaces and volumetric variation.",
      "Deterministic procedural noise; not expressible as a short formula using the basic functions.", "noise3(x,y,z)", 3, 3 },
    { FunctionId::Fbm2, "fbm2", "fbm2(x,y)", "normalized multi-octave 2D noise, about -1..1", "Noise",
      "Combines several octaves of deterministic 2D noise into smoother fractal variation for terrain-like surfaces.",
      "Deterministic multi-octave noise; not expressible as a short formula using the basic functions.", "fbm2(x,y)", 2, 2 },
    { FunctionId::Fbm3, "fbm3", "fbm3(x,y,z)", "normalized multi-octave 3D noise, about -1..1", "Noise",
      "Combines several octaves of deterministic 3D noise into normalized fractal variation for organic implicit fields.",
      "Deterministic multi-octave noise; not expressible as a short formula using the basic functions.", "fbm3(x,y,z)", 3, 3 },
});

} // namespace

std::span<const FunctionInfo> functionRegistry() {
    return kFunctions;
}

const FunctionInfo* findFunctionInfo(std::string_view name) {
    for (const FunctionInfo& info : kFunctions) {
        if (std::string_view(info.name) == name) {
            return &info;
        }
    }
    return nullptr;
}

bool isBuiltinFunction(std::string_view name) {
    return findFunctionInfo(name) != nullptr;
}

} // namespace XpressFormula::Core
